
export const COUNTRIES_LIST = [
    { name: "Choose your country", code: "" },
    { name: "Argentina", code: "AR", phoneCode: "+54" },
    { name: "Australia", code: "AU", phoneCode: "+61" },
    { name: "Brazil", code: "BR", phoneCode: "+55" },
    { name: "Canada", code: "CA", phoneCode: "+1" },
    { name: "China", code: "CN", phoneCode: "+86" },
    { name: "France", code: "FR", phoneCode: "+33" },
    { name: "Germany", code: "DE", phoneCode: "+49" },
    { name: "India", code: "IN", phoneCode: "+91" },
    { name: "Italy", code: "IT", phoneCode: "+39" },
    { name: "Japan", code: "JP", phoneCode: "+81" },
    { name: "Mexico", code: "MX", phoneCode: "+52" },
    { name: "Netherlands", code: "NL", phoneCode: "+31" },
    { name: "Nigeria", code: "NG", phoneCode: "+234" },
    { name: "Russia", code: "RU", phoneCode: "+7" },
    { name: "South Africa", code: "ZA", phoneCode: "+27" },
    { name: "South Korea", code: "KR", phoneCode: "+82" },
    { name: "Spain", code: "ES", phoneCode: "+34" },
    { name: "Switzerland", code: "CH", phoneCode: "+41" },
    { name: "United Kingdom", code: "GB", phoneCode: "+44" },
    { name: "United States", code: "US", phoneCode: "+1" },
];
